import type { Platform, Prompt, PromptStatus } from "../types";
import type { PromptQuery, PromptResponse } from "./api";
const platforms:Platform[]=["ChatGPT","Gemini","Perplexity","Copilot"];
const statuses:PromptStatus[]=["Mentioned","Not Mentioned","Monitoring"];
const seeds=["Best AI search optimization tools for brands","How can a brand improve ChatGPT visibility?","Best GEO agencies in India","How to get cited by Perplexity?","AI search optimization platform comparison","Best digital marketing tools for AI discovery","How does generative engine optimization work?","Best way to track AI brand mentions","How to optimize content for AI search?","Best generative engine optimization strategy","How do AI assistants choose which brands to recommend?","Best AI visibility dashboard for marketing teams"];
const all:Prompt[]=Array.from({length:12000},(_,i)=>({id:i+1,text:`${seeds[i%seeds.length]} #${i+1}`,platform:platforms[i%4],status:statuses[i%3],position:i%9===0?null:(i%8)+1,mentions:12+((i*17)%88),lastChecked:`${(i%12)+1} min ago`}));
const sleep=(ms:number)=>new Promise(r=>setTimeout(r,ms));
export async function localPrompts(query:PromptQuery):Promise<PromptResponse>{await sleep(Math.floor(Math.random()*2801)+200);if(Math.random()<.1)throw new Error("Mock API failure. Please retry the request.");const search=(query.search||"").toLowerCase();let rows=all.filter(p=>(!search||p.text.toLowerCase().includes(search))&&(!query.platform||query.platform==="All"||p.platform===query.platform)&&(!query.status||query.status==="All"||p.status===query.status));const sort=query.sort||"mentions_desc";rows=[...rows].sort((a,b)=>sort==="mentions_asc"?a.mentions-b.mentions||a.id-b.id:sort==="position_asc"?(a.position??999)-(b.position??999)||a.id-b.id:sort==="position_desc"?(b.position??-1)-(a.position??-1)||a.id-b.id:sort==="id_asc"?a.id-b.id:sort==="id_desc"?b.id-a.id:b.mentions-a.mentions||a.id-b.id);const page=Math.max(1,query.page||1),pageSize=Math.min(50,Math.max(10,query.pageSize||25)),total=rows.length,totalPages=Math.max(1,Math.ceil(total/pageSize)),safe=Math.min(page,totalPages);return{items:rows.slice((safe-1)*pageSize,safe*pageSize),total,page:safe,pageSize,totalPages};}
export async function localPrompt(id:number):Promise<Prompt>{await sleep(350);const p=all.find(x=>x.id===id);if(!p)throw new Error("Prompt not found");return p;}
